# Generated by Django 2.1.2 on 2018-10-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_group",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="event group"
                    ),
                ),
                ("template_source", models.TextField(verbose_name="template")),
            ],
            options={"verbose_name": "mail", "verbose_name_plural": "mails"},
        )
    ]
