# Generated by Django 2.1.3 on 2018-11-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("spark_generators", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="generator",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        )
    ]
